# Generated by Django 3.0.3 on 2020-03-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0002_auto_20200212_1432"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagerevision",
            name="difficulty_level",
            field=models.CharField(max_length=1, null=True),
        ),
    ]
